[tool.poetry]
name = "agentic-workflows"
version = "0.0.0"
description = "Experimenting with agent based workflow graphs"
authors = ["Freddy Wordingham <freddy@digilab.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.2.7"
langchain-community = "^0.2.7"
rich = "^13.7.1"
typeguard = "^4.3.0"
langgraph = "^0.1.5"
httpx = "^0.27.0"
langchain-huggingface = "^0.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
