[tool.poetry]
name = "agentic-workflows"
version = "0.0.0"
description = "Experimenting with agent based workflow graphs"
authors = ["Freddy Wordingham <freddy@digilab.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
